name: Check Code Style

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip list

      - name: Run flake8
        run: |
          flake8
